grpc:
  port: 8041
metrics:
  port: 8095
db:
  postgres:
    host: localhost
    port: 60119
    user: postgres
    dbName: testdb
    password: qwerty
    sslmode: disable
auth:
  secretKey: testKey
  refreshTokenTTl: 1h
  accessTokenTTl: 1h