grpc:
  port: 8060
metrics:
  port: 8100
db:
  postgres:
    host: localhost
    port: 53900
    user: postgres
    dbName: testdb
    password: qwerty
    sslmode: disable
auth:
  secretKey: testKey
  refreshTokenTTl: 1h
  accessTokenTTl: 1h