grpc:
  port: 8017
db:
  postgres:
    host: localhost
    port: 55206
    user: postgres
    dbName: testdb
    password: qwerty
    sslmode: disable
auth:
  secretKey: testKey
  refreshTokenTTl: 1h
  accessTokenTTl: 1h