grpc:
  port: 8030
grpcGateway:
  port: 8139
metrics:
  port: 8108
db:
  postgres:
    host: localhost
    port: 60563
    user: postgres
    dbName: testdb
    password: qwerty
    sslmode: disable
auth:
  secretKey: testKey
  refreshTokenTTl: 1h
  accessTokenTTl: 1h